"""Fixed limits for the public Minecraft MCP contract.

The LLM selects a goal. These values limit how the body performs that goal.
Tool descriptions receive the same values through named placeholders.
"""

# Perception
FLOAT_PRECISION = 2

OBSERVE_RADIUS_BLOCKS = 8
FIND_BLOCK_HORIZONTAL_BLOCKS = 32
FIND_BLOCK_UP_BLOCKS = 16
FIND_BLOCK_DOWN_BLOCKS = 24
FIND_BLOCK_RESULT_LIMIT = 16
INTERACTABLE_RADIUS_BLOCKS = 16
INTERACTABLE_RESULT_LIMIT = 32
RAYTRACE_DISTANCE_BLOCKS = 256
HORIZON_HEADING_COUNT = 24
HORIZON_PITCHES_DEGREES = (15, 0, -15)
RECIPE_RESULT_LIMIT = 32
VISIBLE_AREA_HORIZONTAL_BLOCKS = 32
VISIBLE_AREA_UP_BLOCKS = 16
VISIBLE_AREA_DOWN_BLOCKS = 24
LOCAL_PATH_DISTANCE_BLOCKS = 32
PATH_SEARCH_SECONDS = 8
DIG_SOUND_RADIUS_BLOCKS = 16

# World actions
STATE_SYNC_SECONDS = 30
RESPAWN_SECONDS = 30
FURNACE_DISTANCE_BLOCKS = 8
BUILD_DISTANCE_BLOCKS = 32
BUILD_CELL_LIMIT = 512
MINE_BLOCK_SECONDS = 60
ATTACK_HIT_LIMIT = 25
MINE_VEIN_BLOCK_LIMIT = 16
PILLAR_UP_BLOCK_LIMIT = 8

# Movement
FINE_CONTROL_MILLISECONDS = 250
VISIBLE_WALK_SECONDS = 60
VISIBLE_WALK_TOLERANCE_BLOCKS = 3
SURFACE_WALK_SECONDS = 120
EXACT_WALK_SECONDS = 600
EXACT_WALK_TOLERANCE_BLOCKS = 3

# Agent support
WAYPOINT_CAPACITY = 6
SKILL_SECONDS = 600
RECALL_RESULT_LIMIT = 10


DOC_CONSTANTS = {
    name: value
    for name, value in globals().copy().items()
    if name.isupper() and name != "DOC_CONSTANTS"
}
